camera_info:
  focal_length_x: 1345.200806
  focal_length_y: 1353.838257
  image_width: 800
  image_height: 600
stop_line_positions:
    - [8.0, 16.2]

inference:
  frozen_model_path: 'data/saved_models/model_real/frozen_inference_graph.pb'
  confidence_threshold: 0.3