camera_info:
  focal_length_x: 1345.200806
  focal_length_y: 1353.838257
  image_width: 800
  image_height: 600
stop_line_positions:
    - [8.0, 16.2]

inference:
  vanilla_model_path: 'data/saved_models/vanilla_detector/ssd_mobilenet_v1_coco/frozen_inference_graph.pb'
  confidence_threshold: 0.15
  is_real: True
  skip_frames: 5 # Number of frames to skip between consecutive detections
